### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by shjang7** [shjang7/reddit_rr#1]
Please review this project and kindly leave a comment. Thanks.

**Comment by igakigongo** [comment]
I am not yet sure about how to help, my only observation was that rails could not load the react app seems like it was not even bundling it. 
Please let us know if you find out anything useful.

Kind regards,
Edward

**Comment by grace-mugoiri** [comment]
I can suggest you use this link and try to follow up what went wrong with your project.
https://dev.to/jean182/rails-api-with-a-frontend-built-in-react-part-i-con

**Comment by shjang7** [comment]
@grace-mugoiri, my project works fine with the local environment, and the issue is only not working in production.
The link doesn't include online production.
I have more questions about react-rails app production, I will reach out to you with slack.

**Comment by johnsonsirv** [comment]
I like how you were able to integrate React into a full-blown rails app while maintaining a very clean code organisation. :+1:  nice work!

About deployment, I think it has to something to do with Heroku and unbundling the apps correctly. If possible, you could test other PaaS and Hosting service providers like Digital Ocean or Google Cloud for free, until we can find a solution to Heroku. :sunglasses:
